
# 6. ????? API ??
# ??? Encoding ? ?? ??? ????? ?
public.api.key=AHxaXGPYDzKorjM5%2BDKMpreaVu5WdvWOIADbPkXIwgSQDckPDc3tqIL7S6oe3xe6Rg4Ql6hJPGgYM01gs8%2BntQ%3D%3D


# ?? ?? ? ??? ??
repair.api.key=AHxaXGPYDzKorjM5%2BDKMpreaVu5WdvWOIADbPkXIwgSQDckPDc3tqIL7S6oe3xe6Rg4Ql6hJPGgYM01gs8%2BntQ%3D%3D